name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Change to the appropriate Python version if needed

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer

      - name: Install Android Development Kit (ADK)
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          mkdir -p $HOME/Android/sdk/cmdline-tools
          unzip -q commandlinetools-linux-7302050_latest.zip -d $HOME/Android/sdk/cmdline-tools
          echo 'export ANDROID_SDK_ROOT=$HOME/Android/sdk' >> $GITHUB_ENV
          echo 'export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin' >> $GITHUB_ENV

      - name: Get Date
        id: get-date
        run: echo "::set-output name=date::$(/bin/date -u '+%Y%m%d')"

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer local directory
        uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Build with Buildozer
        run: buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*
